# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/smc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/smc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/smc.proto\x12\x03smc\"T\n\x0e\x41nalyzeRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x10\n\x08\x65xchange\x18\x03 \x01(\t\x12\r\n\x05limit\x18\x04 \x01(\x05\"\x91\x01\n\x0f\x41nalyzeResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x0c\n\x04side\x18\x03 \x01(\t\x12\x11\n\tentry_low\x18\x04 \x01(\x01\x12\x12\n\nentry_high\x18\x05 \x01(\x01\x12\x11\n\tstop_loss\x18\x06 \x01(\x01\x12\x13\n\x0btake_profit\x18\x07 \x01(\x01\x32\x42\n\nSMCService\x12\x34\n\x07\x41nalyze\x12\x13.smc.AnalyzeRequest\x1a\x14.smc.AnalyzeResponseB\rZ\x0bproto;smcpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.smc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013proto;smcpb'
  _globals['_ANALYZEREQUEST']._serialized_start=24
  _globals['_ANALYZEREQUEST']._serialized_end=108
  _globals['_ANALYZERESPONSE']._serialized_start=111
  _globals['_ANALYZERESPONSE']._serialized_end=256
  _globals['_SMCSERVICE']._serialized_start=258
  _globals['_SMCSERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
