// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/smc.proto

package smcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Exchange      string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_proto_smc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_proto_smc_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AnalyzeRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *AnalyzeRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *AnalyzeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Side          string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	EntryLow      float64                `protobuf:"fixed64,4,opt,name=entry_low,json=entryLow,proto3" json:"entry_low,omitempty"`
	EntryHigh     float64                `protobuf:"fixed64,5,opt,name=entry_high,json=entryHigh,proto3" json:"entry_high,omitempty"`
	StopLoss      float64                `protobuf:"fixed64,6,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	TakeProfit    float64                `protobuf:"fixed64,7,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_proto_smc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_proto_smc_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AnalyzeResponse) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *AnalyzeResponse) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *AnalyzeResponse) GetEntryLow() float64 {
	if x != nil {
		return x.EntryLow
	}
	return 0
}

func (x *AnalyzeResponse) GetEntryHigh() float64 {
	if x != nil {
		return x.EntryHigh
	}
	return 0
}

func (x *AnalyzeResponse) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *AnalyzeResponse) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

var File_proto_smc_proto protoreflect.FileDescriptor

const file_proto_smc_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/smc.proto\x12\x03smc\"x\n" +
	"\x0eAnalyzeRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xd5\x01\n" +
	"\x0fAnalyzeResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x1b\n" +
	"\tentry_low\x18\x04 \x01(\x01R\bentryLow\x12\x1d\n" +
	"\n" +
	"entry_high\x18\x05 \x01(\x01R\tentryHigh\x12\x1b\n" +
	"\tstop_loss\x18\x06 \x01(\x01R\bstopLoss\x12\x1f\n" +
	"\vtake_profit\x18\a \x01(\x01R\n" +
	"takeProfit2B\n" +
	"\n" +
	"SMCService\x124\n" +
	"\aAnalyze\x12\x13.smc.AnalyzeRequest\x1a\x14.smc.AnalyzeResponseB\x13Z\x11proto/smcpb;smcpbb\x06proto3"

var (
	file_proto_smc_proto_rawDescOnce sync.Once
	file_proto_smc_proto_rawDescData []byte
)

func file_proto_smc_proto_rawDescGZIP() []byte {
	file_proto_smc_proto_rawDescOnce.Do(func() {
		file_proto_smc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smc_proto_rawDesc), len(file_proto_smc_proto_rawDesc)))
	})
	return file_proto_smc_proto_rawDescData
}

var file_proto_smc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_smc_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: smc.AnalyzeRequest
	(*AnalyzeResponse)(nil), // 1: smc.AnalyzeResponse
}
var file_proto_smc_proto_depIdxs = []int32{
	0, // 0: smc.SMCService.Analyze:input_type -> smc.AnalyzeRequest
	1, // 1: smc.SMCService.Analyze:output_type -> smc.AnalyzeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_smc_proto_init() }
func file_proto_smc_proto_init() {
	if File_proto_smc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smc_proto_rawDesc), len(file_proto_smc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smc_proto_goTypes,
		DependencyIndexes: file_proto_smc_proto_depIdxs,
		MessageInfos:      file_proto_smc_proto_msgTypes,
	}.Build()
	File_proto_smc_proto = out.File
	file_proto_smc_proto_goTypes = nil
	file_proto_smc_proto_depIdxs = nil
}
